import Head from 'next/head'
import Navbar from '../components/Navbar'

import axios from 'axios'
import Card from '../components/Card'

export default function Home({genres, popularMovies}) {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar genres={genres} />

      <div className="container flex flex-wrap justify-between items-center mx-auto mt-20">
        {popularMovies.map((movie, key) => {
          return (
            <div key={key}>
              <Card popularMovies={movie} />
            </div>
          )
        })}
      </div>
            
    </div>

  )
}

export async function getStaticProps(context) {

  const requestGenres = await axios.get(`https://api.themoviedb.org/3/genre/movie/list?api_key=${process.env.API_KEY}&language=en-US`)
  const { data } = requestGenres
  
  const requestPopularMovies = await axios.get(`https://api.themoviedb.org/3/movie/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`)
  const { results } = await requestPopularMovies.data
  
  return {
      props: {
        genres: data.genres,
        popularMovies: results
      }
  }

}